### ISSUE TITLE
xcbproto for XIM

### ISSUE THREAD

**Issue by kanryu** [fcitx/xcb-imdkit#14]
Hi,

I was looking into the protocols that xcb implements and found your library.

https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/tree/master/src?ref_type=heads

I can't find the xim protocol definition that xcb-imdkit implements, but does it exist somewhere?

**Comment by wengxt** [comment]
https://www.x.org/releases/X11R7.6/doc/libX11/specs/XIM/xim.html

But there are parts that are only implementation defined in libx11.

**Comment by kanryu** [comment]
Thank you. I already have the original xorg specification XML. But the schema is not compatible with xcbproto.

I need XIM XML for xcbproto.

Specifically, xgb, which is an xcb clone implemented in Go language, automatically generates read/write information for each protocol from xcbproto's XML. Therefore, if I can get XIM XML in xcbproto format, he will be able to read and write XIM.

**Comment by wengxt** [comment]
XIM is not a X extension. The actual message is almost embedded in X Client Message.  I doubt it could be supported by xcbproto.

I'm not aware of such a XML file that exists.
