### ISSUE TITLE
Using xcb-imdkit (e.g. test_client) with ibus

### ISSUE THREAD

**Issue by johnbeard** [fcitx/xcb-imdkit#7]
I'm hoping to use xcb-imdkit to enable XIM support for an XCB program. I have tried to connect to the running ibus server on my machine by adjusting the `test_client` program to do:

    xcb_xim_create(c, screen_default_nbr, "@im=ibus");

This doesn't seem to work, all I get is:

    -- XIM_OPEN_REPLY
    -- XIM_QUERY_EXTENSION_REPLY

And then `xcb_xim_filter_event` doesn't return true again.
Should it be possible to connect `test_client` to ibus in this way?

**Comment by wengxt** [comment]
Looks like there's a issue of protocol inconsistency between this and ibus

IBus has two BIT8 field here, while this implementation expect two BIT16. 
https://github.com/ibus/ibus/blob/master/util/IMdkit/i18nIMProto.c#L109

Checking which one is the correct one...
